name: 3D Profile Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: output-branch
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate custom 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Ganesh40292
          SETTING_JSON: custom-3d-settings.json

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: output
          commit_message: "Update 3D contribution graph"
          create_branch: true
          push_options: "--force"
